ris:
    dataset_valid_starting: '01/01/2015'
    dataset_valid_ending: '01/01/2020'

models:
    harvey_logistic_reg:
        name: harvey_logistic_reg
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'no_show_before_sq'
                    - 'sched_days_advanced'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'age'
                    - 'close_to_usz'
                    - 'male'
                    - 'female'
                    - 'age_sq'
                    - 'sched_days_advanced_sq'
                    - 'distance_to_usz_sq'
                    - 'sched_2_days'
                    - 'age_20_60'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 3  # 5
        Architecture:
            flavor: LogisticRegression
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: RandomSearchTuner
            config:
                hyperparameters:
                    penalty: ['l1', 'l2', 'elasticnet', 'none']
                    C: [0, 1, 10]
                    solver: ['liblinear', 'lbfgs']
                search_type: random
                num_cv_folds: 2  # 5
                num_iters: 2  # 150
                scoring_function: f1_macro
#                run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    harvey_random_forest:
        name: harvey_random_forest
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'no_show_before_sq'
                    - 'sched_days_advanced'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'age'
                    - 'close_to_usz'
                    - 'male'
                    - 'female'
                    - 'age_sq'
                    - 'sched_days_advanced_sq'
                    - 'distance_to_usz_sq'
                    - 'sched_2_days'
                    - 'age_20_60'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 2  # 5
        Architecture:
            flavor: RandomForestClassifier
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: RandomSearchTuner
            config:
                hyperparameters:
                    n_estimators:
                        parse_np_linspace:
                            start: 200
                            stop: 2000
                            num: 10
                    max_features: ['auto', 'sqrt']
                    max_depth:
                        parse_np_linspace:
                            start: 10
                            stop: 110
                            num: 11
                    min_samples_split: [2, 4, 6, 8, 10]
                    min_samples_leaf: [1, 2, 5, 10]
                    bootstrap: [true, false]
                search_type: random
                num_cv_folds: 2  # 5
                num_iters: 2  # 150
                scoring_function: f1_macro
#            run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    logistic_regression:
        name: logistic_regression
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'sched_days_advanced'
                    #- 'month'
                    - 'age'
                    - 'modality'
                    - 'sex'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'day_of_week_str'
                    - 'marital'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 5
        Architecture:
            flavor: Pipeline
            config:
                steps:
                  - flavor: sklearn.compose.ColumnTransformer
                    name: 'preprocessing'
                    config:
                        steps:
                            - name: 'scaler'
                              flavor: sklearn.preprocessing.StandardScaler
                              config:
                                with_mean: True
                              args:
                                columns:
                                    - 'no_show_before'
                                    - 'sched_days_advanced'
                                    - 'age'
                                    - 'hour_sched'
                                    - 'distance_to_usz'
                            - name: 'onehot'
                              flavor: sklearn.preprocessing.OneHotEncoder
                              config:
                                  handle_unknown: 'ignore'
                              args:
                                  columns:
                                      - 'marital'
                                      - 'modality'
                                      - 'sex'
                                      - 'day_of_week_str'
                  - flavor: LogisticRegression
                    name: 'classifier'
                    config:
                        penalty: 'l1'
                        solver: 'liblinear'
                        class_weight: 'balanced'
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: BayesianTuner
            config:
                hyperparameters:
                    classifier__C:
                        parse_hp_uniform:
                            start: 0
                            end: 10
                search_type: bayesian
                num_cv_folds: 5
                num_iters: 50
                scoring_function: log_loss
                verbose: 0
                hyperopt_timeout: 10000000
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    random_forest:
        name: random_forest
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'sched_days_advanced'
                    #- 'month'
                    - 'age'
                    - 'modality'
                    - 'sex'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'day_of_week_str'
                    - 'marital'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 5
        Architecture:
            flavor: Pipeline
            config:
                steps:
                  - flavor: sklearn.compose.ColumnTransformer
                    name: 'preprocessing'
                    config:
                        steps:
                            - name: 'scaler'
                              flavor: sklearn.preprocessing.StandardScaler
                              config:
                                with_mean: True
                              args:
                                columns:
                                    - 'no_show_before'
                                    - 'sched_days_advanced'
                                    - 'age'
                                    - 'hour_sched'
                                    - 'distance_to_usz'
                            - name: 'onehot'
                              flavor: sklearn.preprocessing.OneHotEncoder
                              config:
                                  handle_unknown: 'ignore'
                              args:
                                  columns:
                                      - 'marital'
                                      - 'modality'
                                      - 'sex'
                                      - 'day_of_week_str'
                  - flavor: RandomForestClassifier
                    name: 'classifier'
                    config:
                        class_weight: 'balanced'
                        n_estimators: 400
                        random_state: 94
                        n_jobs: -1
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: BayesianTuner
            config:
                hyperparameters:
                    classifier__max_depth:
                        parse_hp_uniformint:
                            start: 2
                            end: 20
                    classifier__min_samples_split:
                        parse_hp_uniformint:
                            start: 2
                            end: 20
                    classifier__max_features:
                        parse_hp_choice:
                            choice_list:
                                - 'auto'
                                - 'sqrt'
                                - 'log2'
                search_type: bayesian
                num_cv_folds: 5
                num_iters: 50  # 150
                scoring_function: log_loss
                verbose: 0
                hyperopt_timeout: 10000000
        #            run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    xgboost:
        name: xgboost
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'sched_days_advanced'
                    #- 'month'
                    - 'age'
                    - 'modality'
                    - 'sex'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'day_of_week_str'
                    - 'marital'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 5
        Architecture:
            flavor: Pipeline
            config:
                steps:
                  - flavor: sklearn.compose.ColumnTransformer
                    name: 'preprocessing'
                    config:
                        steps:
                          - name: 'scaler'
                            flavor: sklearn.preprocessing.StandardScaler
                            config:
                                with_mean: True
                            args:
                                columns:
                                  - 'no_show_before'
                                  - 'sched_days_advanced'
                                  -  'age'
                                  -  'hour_sched'
                                  - 'distance_to_usz'
                          - name: 'onehot'
                            flavor: sklearn.preprocessing.OneHotEncoder
                            config:
                                handle_unknown: 'ignore'
                            args:
                                columns:
                                  - 'marital'
                                  - 'modality'
                                  - 'sex'
                                  - 'day_of_week_str'
                  - flavor: XGBClassifier
                    name: 'classifier'
                    config:
                      eval_metric: 'logloss'
                      use_label_encoder: False
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: BayesianTuner
            config:
                hyperparameters:
                    classifier__n_estimators:
                        parse_hp_uniformint:
                            start: 10
                            end: 400
                    classifier__max_depth:
                        parse_hp_uniformint:
                            start: 2
                            end: 20
                search_type: bayesian
                num_cv_folds: 5
                num_iters: 50  # 150
                scoring_function: log_loss
                verbose: 0
                hyperopt_timeout: 10000000
        #            run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    neural_net:
        name: neural_net
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'sched_days_advanced'
                    #- 'month'
                    - 'age'
                    - 'modality'
                    - 'sex'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'day_of_week_str'
                    - 'marital'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 5
        Architecture:
            flavor: Pipeline
            config:
                steps:
                  - flavor: sklearn.compose.ColumnTransformer
                    name: 'preprocessing'
                    config:
                        steps:
                          - name: 'scaler'
                            flavor: sklearn.preprocessing.StandardScaler
                            config:
                                with_mean: True
                            args:
                                columns:
                                  - 'no_show_before'
                                  - 'sched_days_advanced'
                                  -  'age'
                                  -  'hour_sched'
                                  - 'distance_to_usz'
                          - name: 'onehot'
                            flavor: sklearn.preprocessing.OneHotEncoder
                            config:
                                handle_unknown: 'ignore'
                            args:
                                columns:
                                  - 'marital'
                                  - 'modality'
                                  - 'sex'
                                  - 'day_of_week_str'
                  - flavor: sklearn.preprocessing.FunctionTransformer
                    name: 'tofloat'
                    args:
                        accept_sparse: True
                        func: mridle.utilities.data_processing.tofloat32
                  - flavor: skorch.NeuralNet
                    name: 'classifier'
                    config:
                      lr: 0.0001
                      max_epochs: 100
                      verbose: 0
                      iterator_train__shuffle: True
                    args:
                        module:
                            flavor: mridle.experiment.architectures.MLP.MLP
                            config:
                                input_layer_size: 45
                                hidden_layer_size: 30
                                dropout_p: 0
                        criterion:
                            flavor: torch.nn.BCELoss
                            instantiate: False
                        optimizer:
                            flavor: torch.optim.Adam
                            instantiate: False
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: BayesianTuner
            config:
                hyperparameters:
                    classifier__batch_size:
                        parse_hp_choice:
                            choice_list:
                                - 16
                                - 32
                                - 62
                                - 128
                                - 256
                    classifier__lr:
                        parse_hp_choice:
                            choice_list:
                                - 0.0001
                                - 0.001
                                - 0.01
                                - 0.1
                search_type: bayesian
                num_cv_folds: 5
                num_iters: 2  # 150
                scoring_function: log_loss
                verbose: 0
                hyperopt_timeout: 10000000
        #            run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss
