ris:
    dataset_valid_starting: '01/01/2015'
    dataset_valid_ending: '01/01/2020'

models:
    harvey_logistic_reg:
        name: harvey_logistic_reg
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'no_show_before_sq'
                    - 'sched_days_advanced'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'age'
                    - 'close_to_usz'
                    - 'male'
                    - 'female'
                    - 'age_sq'
                    - 'sched_days_advanced_sq'
                    - 'distance_to_usz_sq'
                    - 'sched_2_days'
                    - 'age_20_60'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 3  # 5
        Architecture:
            flavor: LogisticRegression
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: RandomSearchTuner
            config:
                hyperparameters:
                    penalty: ['l1', 'l2', 'elasticnet', 'none']
                    C: [0, 1, 10]
                    solver: ['liblinear', 'lbfgs']
                search_type: random
                num_cv_folds: 2  # 5
                num_iters: 2  # 150
                scoring_function: f1_macro
#                run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    harvey_random_forest:
        name: harvey_random_forest
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'no_show_before_sq'
                    - 'sched_days_advanced'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'age'
                    - 'close_to_usz'
                    - 'male'
                    - 'female'
                    - 'age_sq'
                    - 'sched_days_advanced_sq'
                    - 'distance_to_usz_sq'
                    - 'sched_2_days'
                    - 'age_20_60'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 2  # 5
        Architecture:
            flavor: RandomForestClassifier
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: RandomSearchTuner
            config:
                hyperparameters:
                    n_estimators:
                        parse_np_linspace:
                            start: 200
                            stop: 2000
                            num: 10
                    max_features: ['auto', 'sqrt']
                    max_depth:
                        parse_np_linspace:
                            start: 10
                            stop: 110
                            num: 11
                    min_samples_split: [2, 4, 6, 8, 10]
                    min_samples_leaf: [1, 2, 5, 10]
                    bootstrap: [true, false]
                search_type: random
                num_cv_folds: 2  # 5
                num_iters: 2  # 150
                scoring_function: f1_macro
#            run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss

    harvey_random_forest_hp:
        name: harvey_random_forest_hp
        verbose: false
        DataSet:
            flavor: DataSet
            config:
                features:
                    - 'no_show_before'
                    - 'no_show_before_sq'
                    - 'sched_days_advanced'
                    - 'hour_sched'
                    - 'distance_to_usz'
                    - 'age'
                    - 'close_to_usz'
                    - 'male'
                    - 'female'
                    - 'age_sq'
                    - 'sched_days_advanced_sq'
                    - 'distance_to_usz_sq'
                    - 'sched_2_days'
                    - 'age_20_60'
                target: NoShow
        Stratifier:
            flavor: PartitionedLabelStratifier
            config:
                n_partitions: 5  # 5
        Architecture:
            flavor: RandomForestClassifier
                config:
                    class_weight: 'balanced'
        Trainer:
            flavor: Trainer
        Tuner:
            flavor: BayesianTuner
            config:
                hyperparameters:
                    n_estimators:
                        parse_hp_choice:
                            choice_list: [10, 100, 400]
                    max_depth:
                        parse_hp_choice:
                            choice_list: [2, 4, 10, 50, 100]
                    min_samples_split:
                        parse_hp_uniformint:
                            start: 2
                            end: 10
                search_type: bayesian
                num_cv_folds: 5  # 5
                num_iters: 100  # 150
                scoring_function: auprc
                verbose: 0
                hyperopt_timeout: 1000000
#            run_hyperparam_search: true
        Metrics:
            - flavor: F1_Macro
              config:
                  classification_cutoff: 0.5
            - flavor: AUPRC
            - flavor: AUROC
            - flavor: LogLoss