models:
  harvey:
    name: harvey
    verbose: false
    label_key: NoShow
    hyperparameters: {}
    search_type: random
    scoring_fn: f1_score
    run_hyperparam_search: false
    features:
        - 'no_show_before'
        - 'no_show_before_sq'
        - 'sched_days_advanced'
        - 'hour_sched'
        # - 'distance_to_usz'
        - 'age'
        # - 'close_to_usz'
        - 'male'
        - 'female'
        - 'age_sq'
        # - 'sched_days_advanced_sq'
        # - 'distance_to_usz_sq'
        - 'sched_2_days'
        - 'age_20_60'
        
