models:
    harvey_random_forest:
        name: harvey_random_forest
        verbose: false
        label_key: NoShow
        hyperparameters:
            n_estimators:
                start: 200
                stop: 2000
                num: 10
            max_features: ['auto', 'sqrt']
            max_depth:
                start: 10
                stop: 110
                num: 11
            min_samples_split: [2, 4, 6, 8, 10]
            min_samples_leaf: [1, 2, 5, 10]
            bootstrap: [True, False]
        search_type: random
        scoring_fn: f1_score
        run_hyperparam_search: false
        features:
            - 'no_show_before'
            - 'no_show_before_sq'
            - 'sched_days_advanced'
            - 'hour_sched'
            # - 'distance_to_usz'
            - 'age'
            # - 'close_to_usz'
            - 'male'
            - 'female'
            - 'age_sq'
            # - 'sched_days_advanced_sq'
            # - 'distance_to_usz_sq'
            - 'sched_2_days'
            - 'age_20_60'
